<?php
/**
* SLDirect
* Directorio de Empresas, Servicios y Demandas
* ----------------------------------------------------------------------------------
* Copyright  (C) 2008-2009 CENATIC, Centro Nacional
*                          de Referencia en TICs de
*                          Fuentes Abiertas.
* ----------------------------------------------------------------------------------
*
* This file is part of SLDirect
*
* SLDirect is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; version 2 of the License.
*
* SLDirect is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with bbPress; if not, write to the Free Software
* Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*
* ----------------------------------------------------------------------------------
*
* @copyright 2008-2009 CENATIC
* @license   http://www.gnu.org/licenses/gpl.txt GNU General Public License v2
* @link      http://www.cenatic.es
*
**/

/* File Auto-generated by Webalianza CodeGen 0.1 <luis@webalianza.com> on 2008-09-12 07:13 */
require_once("models/organizacionSede.model.php");
require_once("models/organizacion.model.php");

class provincia extends model {

	var $id;
	var $nombre;

	function __construct(){
		$this->setRelativeTable("provincias");
		$this->children("organizacionSede","provincia_id");
		$this->children("organizacion","provincia_id");
	}

	function parseValidation(){
		$error_fields = array();;
		$this->nombre = mysql_escape_string($this->nombre);

		if (count($error_fields) >0) throw new InvalidModelException(implode(',',$error_fields));
	}

	function onInsert(){
		$this->parseValidation();
	}

	function onUpdate(){
		$this->parseValidation();
	}
}


/*
---BEGIN GENTAG---
YTo1OntzOjI6ImRiIjtzOjc6ImNlbmF0aWMiO3M6NToidGFibGUiO3M6MTA6InByb3ZpbmNpYXMiO3M6NToiY2xhc3MiO3M6OToi
cHJvdmluY2lhIjtzOjg6ImNoaWxkcmVuIjthOjY6e2k6MDthOjI6e3M6NToibW9kZWwiO3M6MTY6Im9yZ2FuaXphY2lvblNlZGUi
O3M6Mzoia2V5IjtzOjEyOiJwcm92aW5jaWFfaWQiO31pOjE7YToyOntzOjU6Im1vZGVsIjtzOjEyOiJvcmdhbml6YWNpb24iO3M6
Mzoia2V5IjtzOjEyOiJwcm92aW5jaWFfaWQiO31pOjI7YToyOntzOjU6Im1vZGVsIjtzOjA6IiI7czozOiJrZXkiO3M6MDoiIjt9
aTozO2E6Mjp7czo1OiJtb2RlbCI7czowOiIiO3M6Mzoia2V5IjtzOjA6IiI7fWk6NDthOjI6e3M6NToibW9kZWwiO3M6MDoiIjtz
OjM6ImtleSI7czowOiIiO31pOjU7YToyOntzOjU6Im1vZGVsIjtzOjA6IiI7czozOiJrZXkiO3M6MDoiIjt9fXM6MjoiZmsiO2E6
Njp7aTowO2E6Mzp7czo1OiJmaWVsZCI7czowOiIiO3M6NToibW9kZWwiO3M6MDoiIjtzOjc6ImNhcHRpb24iO3M6MDoiIjt9aTox
O2E6Mzp7czo1OiJmaWVsZCI7czowOiIiO3M6NToibW9kZWwiO3M6MDoiIjtzOjc6ImNhcHRpb24iO3M6MDoiIjt9aToyO2E6Mzp7
czo1OiJmaWVsZCI7czowOiIiO3M6NToibW9kZWwiO3M6MDoiIjtzOjc6ImNhcHRpb24iO3M6MDoiIjt9aTozO2E6Mzp7czo1OiJm
aWVsZCI7czowOiIiO3M6NToibW9kZWwiO3M6MDoiIjtzOjc6ImNhcHRpb24iO3M6MDoiIjt9aTo0O2E6Mzp7czo1OiJmaWVsZCI7
czowOiIiO3M6NToibW9kZWwiO3M6MDoiIjtzOjc6ImNhcHRpb24iO3M6MDoiIjt9aTo1O2E6Mzp7czo1OiJmaWVsZCI7czowOiIi
O3M6NToibW9kZWwiO3M6MDoiIjtzOjc6ImNhcHRpb24iO3M6MDoiIjt9fX0=
---END GENTAG---
*/
