<?php
/**
* SLDirect
* Directorio de Empresas, Servicios y Demandas
* ----------------------------------------------------------------------------------
* Copyright  (C) 2008-2009 CENATIC, Centro Nacional
*                          de Referencia en TICs de
*                          Fuentes Abiertas.
* ----------------------------------------------------------------------------------
*
* This file is part of SLDirect
*
* SLDirect is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; version 2 of the License.
*
* SLDirect is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with bbPress; if not, write to the Free Software
* Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*
*----------------------------------------------------------------------------------
*
* @copyright 2008-2009 CENATIC
* @license   http://www.gnu.org/licenses/gpl.txt GNU General Public License v2
* @link      http://www.cenatic.es
*
**/

/* File Auto-generated by Webalianza CodeGen 0.1 <luis@webalianza.com> on 2008-09-12 07:00 */
require_once("models/organizacionSede.model.php");
require_once("models/capacidadOfertaOrganizacion.model.php");
require_once("models/capacidadDemandaOrganizacion.model.php");
require_once("models/organizacionAsociacion.model.php");
require_once("models/provincia.model.php");
require_once("models/formaJuridica.model.php");

class organizacion extends model {

	var $id;
	var $nombre;
	var $descripcion;
	var $web;
	var $direccion;
	var $localidad;
	var $formaJuridica_id;
	var $organizacionClasificacion_id;
	var $provincia_id;
	var $certificacionesCalidad;
	var $partners;
	var $participacionImasD;
	var $relacionesComunidad;
	var $logo_url;
	var $codigoPostal;
	var $cif;
	var $anoConstitucion;
	var $username;
	var $password;
	var $hashCreacion;

	function __construct(){
		$this->setRelativeTable("organizaciones");
		$this->children("organizacionSede","organizacion_id");
		$this->children("capacidadOfertaOrganizacion","organizacion_id");
		$this->children("capacidadDemandaOrganizacion","organizacion_id");
		$this->children("organizacionAsociacion","organizacion_id");
		$this->Foreign("provincia_id","provincia","nombre");
		$this->Foreign("formaJuridica_id","formaJuridica","nombre");
		$this->Foreign("organizacionClasificacion_id","organizacionClasificacion","nombre");
	}

	function parseValidation(){
		$error_fields = array();
		if ($this->web != "" && !preg_match ("|^http(s)?://[a-z0-9-]+(.[a-z0-9-]+)*(:[0-9]+)?(/.*)?$|i", $this->web)) { $error_fields[] = "web"; }
		if ($this->logo_url != "" && !preg_match ("|^http(s)?://[a-z0-9-]+(.[a-z0-9-]+)*(:[0-9]+)?(/.*)?$|i", $this->logo_url)) { $error_fields[] = "logo_url"; }
		$this->logo_url = mysql_escape_string($this->logo_url);
		$this->nombre = mysql_escape_string($this->nombre);
		$this->descripcion = mysql_escape_string($this->descripcion);
		$this->web = mysql_escape_string($this->web);
		$this->direccion = mysql_escape_string($this->direccion);
		$this->localidad = mysql_escape_string($this->localidad);
		if ($this->provincia_id == '') $this->provincia_id = 0;
		if (is_numeric($this->provincia_id)){
			if ($this->provincia_id != (int)$this->provincia_id)
				$error_fields[]="provincia_id";
		}else{
			$error_fields[]="provincia_id";
		}
		if ($this->codigoPostal == '') $this->codigoPostal = 0;
		if (is_numeric($this->codigoPostal)){
			if ($this->codigoPostal != (int)$this->codigoPostal)
				$error_fields[]="codigoPostal";
		}else{
			$error_fields[]="codigoPostal";
		}
		$this->cif = mysql_escape_string($this->cif);
		if ($this->anoConstitucion == '') $this->anoConstitucion = 0;
		if (is_numeric($this->anoConstitucion)){
			if ($this->anoConstitucion != (int)$this->anoConstitucion)
				$error_fields[]="anoConstitucion";
		}else{
			$error_fields[]="anoConstitucion";
		}
		$this->username = mysql_escape_string($this->username);
		$this->password = mysql_escape_string($this->password);
		$this->hashCreacion = mysql_escape_string($this->hashCreacion);
		$provincia_check = new provincia();
		$provincia_check->open($this->provincia_id);
		if ($provincia_check->id != $this->provincia_id) $error_fields[]="provincia_id";
		$formaJuridica_check = new formaJuridica();
		$formaJuridica_check->open($this->formaJuridica_id);
		if ($formaJuridica_check->id != $this->formaJuridica_id) $error_fields[]="formaJuridica_id";
		$organizacionClasificacion_check = new organizacionClasificacion();
		$organizacionClasificacion_check->open($this->organizacionClasificacion_id);
		if ($organizacionClasificacion_check->id != $this->organizacionClasificacion_id) $error_fields[]="organizacionClasificacion_id";
		
		if (count($error_fields) >0) throw new InvalidModelException(implode(',',$error_fields));
	}

	function onInsert(){
		$this->parseValidation();
	}

	function onUpdate(){
		$this->parseValidation();
	}
}


/*
---BEGIN GENTAG---
YTo1OntzOjI6ImRiIjtzOjc6ImNlbmF0aWMiO3M6NToidGFibGUiO3M6MTQ6Im9yZ2FuaXphY2lvbmVzIjtzOjU6ImNsYXNzIjtz
OjEyOiJvcmdhbml6YWNpb24iO3M6ODoiY2hpbGRyZW4iO2E6Njp7aTowO2E6Mjp7czo1OiJtb2RlbCI7czoxNjoib3JnYW5pemFj
aW9uU2VkZSI7czozOiJrZXkiO3M6MTU6Im9yZ2FuaXphY2lvbl9pZCI7fWk6MTthOjI6e3M6NToibW9kZWwiO3M6Mjc6ImNhcGFj
aWRhZE9mZXJ0YU9yZ2FuaXphY2lvbiI7czozOiJrZXkiO3M6MTU6Im9yZ2FuaXphY2lvbl9pZCI7fWk6MjthOjI6e3M6NToibW9k
ZWwiO3M6Mjg6ImNhcGFjaWRhZERlbWFuZGFPcmdhbml6YWNpb24iO3M6Mzoia2V5IjtzOjE1OiJvcmdhbml6YWNpb25faWQiO31p
OjM7YToyOntzOjU6Im1vZGVsIjtzOjIyOiJvcmdhbml6YWNpb25Bc29jaWFjaW9uIjtzOjM6ImtleSI7czoxNToib3JnYW5pemFj
aW9uX2lkIjt9aTo0O2E6Mjp7czo1OiJtb2RlbCI7czowOiIiO3M6Mzoia2V5IjtzOjA6IiI7fWk6NTthOjI6e3M6NToibW9kZWwi
O3M6MDoiIjtzOjM6ImtleSI7czowOiIiO319czoyOiJmayI7YTo2OntpOjA7YTozOntzOjU6ImZpZWxkIjtzOjEyOiJwcm92aW5j
aWFfaWQiO3M6NToibW9kZWwiO3M6OToicHJvdmluY2lhIjtzOjc6ImNhcHRpb24iO3M6Njoibm9tYnJlIjt9aToxO2E6Mzp7czo1
OiJmaWVsZCI7czowOiIiO3M6NToibW9kZWwiO3M6MDoiIjtzOjc6ImNhcHRpb24iO3M6MDoiIjt9aToyO2E6Mzp7czo1OiJmaWVs
ZCI7czowOiIiO3M6NToibW9kZWwiO3M6MDoiIjtzOjc6ImNhcHRpb24iO3M6MDoiIjt9aTozO2E6Mzp7czo1OiJmaWVsZCI7czow
OiIiO3M6NToibW9kZWwiO3M6MDoiIjtzOjc6ImNhcHRpb24iO3M6MDoiIjt9aTo0O2E6Mzp7czo1OiJmaWVsZCI7czowOiIiO3M6
NToibW9kZWwiO3M6MDoiIjtzOjc6ImNhcHRpb24iO3M6MDoiIjt9aTo1O2E6Mzp7czo1OiJmaWVsZCI7czowOiIiO3M6NToibW9k
ZWwiO3M6MDoiIjtzOjc6ImNhcHRpb24iO3M6MDoiIjt9fX0=
---END GENTAG---
*/
