<?php
/**
* SLDirect
* Directorio de Empresas, Servicios y Demandas
* ----------------------------------------------------------------------------------
* Copyright  (C) 2008-2009 CENATIC, Centro Nacional
*                          de Referencia en TICs de
*                          Fuentes Abiertas.
* ----------------------------------------------------------------------------------
*
* This file is part of SLDirect
*
* SLDirect is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; version 2 of the License.
*
* SLDirect is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with bbPress; if not, write to the Free Software
* Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*
* ----------------------------------------------------------------------------------
*
* @copyright 2008-2009 CENATIC
* @license   http://www.gnu.org/licenses/gpl.txt GNU General Public License v2
* @link      http://www.cenatic.es
*
**/

/* File Auto-generated by Webalianza CodeGen 0.1 <luis@webalianza.com> on 2008-09-12 07:05 */
require_once("models/capacidadOfertaOrganizacion.model.php");
require_once("models/capacidadDemandaOrganizacion.model.php");

class sector extends model {

	var $id;
	var $nombre;

	function __construct(){
		$this->setRelativeTable("sectores");
		$this->children("capacidadOfertaOrganizacion","sector_id");
		$this->children("capacidadDemandaOrganizacion","sector_id");
	}

	function parseValidation(){
		$error_fields = array();;
		$this->nombre = mysql_escape_string($this->nombre);

		if (count($error_fields) >0) throw new InvalidModelException(implode(',',$error_fields));
	}

	function onInsert(){
		$this->parseValidation();
	}

	function onUpdate(){
		$this->parseValidation();
	}
}


/*
---BEGIN GENTAG---
YTo1OntzOjI6ImRiIjtzOjc6ImNlbmF0aWMiO3M6NToidGFibGUiO3M6ODoic2VjdG9yZXMiO3M6NToiY2xhc3MiO3M6Njoic2Vj
dG9yIjtzOjg6ImNoaWxkcmVuIjthOjY6e2k6MDthOjI6e3M6NToibW9kZWwiO3M6Mjc6ImNhcGFjaWRhZE9mZXJ0YU9yZ2FuaXph
Y2lvbiI7czozOiJrZXkiO3M6OToic2VjdG9yX2lkIjt9aToxO2E6Mjp7czo1OiJtb2RlbCI7czoyODoiY2FwYWNpZGFkRGVtYW5k
YU9yZ2FuaXphY2lvbiI7czozOiJrZXkiO3M6OToic2VjdG9yX2lkIjt9aToyO2E6Mjp7czo1OiJtb2RlbCI7czowOiIiO3M6Mzoi
a2V5IjtzOjA6IiI7fWk6MzthOjI6e3M6NToibW9kZWwiO3M6MDoiIjtzOjM6ImtleSI7czowOiIiO31pOjQ7YToyOntzOjU6Im1v
ZGVsIjtzOjA6IiI7czozOiJrZXkiO3M6MDoiIjt9aTo1O2E6Mjp7czo1OiJtb2RlbCI7czowOiIiO3M6Mzoia2V5IjtzOjA6IiI7
fX1zOjI6ImZrIjthOjY6e2k6MDthOjM6e3M6NToiZmllbGQiO3M6MDoiIjtzOjU6Im1vZGVsIjtzOjA6IiI7czo3OiJjYXB0aW9u
IjtzOjA6IiI7fWk6MTthOjM6e3M6NToiZmllbGQiO3M6MDoiIjtzOjU6Im1vZGVsIjtzOjA6IiI7czo3OiJjYXB0aW9uIjtzOjA6
IiI7fWk6MjthOjM6e3M6NToiZmllbGQiO3M6MDoiIjtzOjU6Im1vZGVsIjtzOjA6IiI7czo3OiJjYXB0aW9uIjtzOjA6IiI7fWk6
MzthOjM6e3M6NToiZmllbGQiO3M6MDoiIjtzOjU6Im1vZGVsIjtzOjA6IiI7czo3OiJjYXB0aW9uIjtzOjA6IiI7fWk6NDthOjM6
e3M6NToiZmllbGQiO3M6MDoiIjtzOjU6Im1vZGVsIjtzOjA6IiI7czo3OiJjYXB0aW9uIjtzOjA6IiI7fWk6NTthOjM6e3M6NToi
ZmllbGQiO3M6MDoiIjtzOjU6Im1vZGVsIjtzOjA6IiI7czo3OiJjYXB0aW9uIjtzOjA6IiI7fX19
---END GENTAG---
*/
